# -*- coding: utf-8 -*-
"""Vaccum_cleaner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CycKKpFvCy4QBv3XWpvE5FvBZnRtYtbR
"""

cleaned = 0
dirt = 0

environment = {"A": ["Dirty", "Dirty"],
               "B": ["Clean", "Dirty"]}
agent_location = "A"

if environment[agent_location][0] == "Dirty":
    cleaned += 1
    dirt += 1
    environment[agent_location][0] = "Clean"
    if environment[agent_location][1] == "Dirty":
      cleaned += 1
      dirt += 1
      environment[agent_location][1] = "Clean"
      agent_location = "B"
    else:
      cleaned += 1
      agent_location = "B"

elif environment[agent_location][0] == "Clean":
    cleaned += 1
    environment[agent_location][0] = "Clean"
    if environment[agent_location][1] == "Dirty":
      cleaned += 1
      dirt += 1
      environment[agent_location][1] = "Clean"
      agent_location = "B"
    else:
      cleaned += 1
      agent_location = "B"

if environment[agent_location][0] == "Dirty":
    cleaned += 1
    dirt += 1
    environment[agent_location][0] = "Clean"
    if environment[agent_location][1] == "Dirty":
      cleaned += 1
      dirt += 1
      environment[agent_location][1] = "Clean"
      agent_location = "A"
    else:
      cleaned += 1
      agent_location = "A"

elif environment[agent_location][0] == "Clean":
    cleaned += 1
    environment[agent_location][0] = "Clean"
    if environment[agent_location][1] == "Dirty":
      cleaned += 1
      dirt += 1
      environment[agent_location][1] = "Clean"
      agent_location = "A"
    else:
      cleaned += 1
      agent_location = "A"

print(environment)

print("Performance: ")
clean_percentage = (cleaned/4)*100
dirt_percentage = (dirt/4)*100
print(f"{clean_percentage}% of tiles have been cleaned")
print(f"{dirt_percentage}% of tiles of dirt has been removed")
